---

- name: Create kafka group
  group:
    name: kafka
    state: present
  tags: kafka

- name: Create kafka user
  user:
    name: kafka
    group: kafka
  tags: kafka

- name: Create kafka installation folder
  file:
    state: directory
    path: "{{kafka_home_folder}}"
    owner: kafka
    group: kafka
  tags: kafka

- name: Create kafka data folder
  file:
    state: directory
    path: "{{kafka_data_folder}}"
    owner: kafka
    group: kafka
  tags: kafka

- name: Create kafka log folder
  file:
    state: directory
    path: "{{kafka_data_folder}}/log"
    owner: kafka
    group: kafka
  tags: kafka

- name: Download kafka
  get_url:
    url: "{{kafka_download_url}}"
    dest: "/tmp/{{kafka_archive_filename}}"
  tags: kafka

- name: Unarchive kafka
  unarchive:
    src: "/tmp/{{kafka_archive_filename}}"
    dest: "{{kafka_home_folder}}"
    extra_opts: ['--strip-components=1']
    remote_src: true
  tags: kafka

- name: Copy kafka server.properties
  template:
    src: server-distributed.properties
    dest: "{{kafka_home_folder}}/config/server-distributed.properties"
  notify: restart kafka
  tags: kafka

- name: Copy kafka-topics-init.sh
  template:
    src: kafka-topics-init.sh
    dest: "/home/vagrant/kafka-topics-init.sh"
    mode: "u+rx"
  tags: kafka

- name: Copy kafka jks-generator.sh
  template:
    src: jks-generator.sh
    dest: "{{kafka_home_folder}}/config/jks-generator.sh"
    mode: "u+rx"
  tags: kafka

- name: Run the jks-generator.sh
  command: "{{kafka_home_folder}}/config/jks-generator.sh"
  tags: kafka

- name: Create kafka service file
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: 644
  tags: kafka

- name: Reload systemd
  command: systemctl daemon-reload
  notify: start kafka
  tags: kafka
