
oracle_java_dir_source: '/usr/local/src'
#oracle_java_set_as_default: yes

oracle_java_version: "8"
oracle_java_version_update: "144"
oracle_java_version_build: "01"
oracle_java_version_uuid: "090f390dda5b47b9b721c7dfaa008135"
oracle_java_version_string: "1.{{oracle_java_version}}.0_{{oracle_java_version_update}}"

oracle_java_home: "/usr/java/jdk{{oracle_java_version_string}}"

oracle_java_os_supported: yes

oracle_java_rpm_filename: "jdk-{{oracle_java_version}}u{{oracle_java_version_update}}-linux-x64.rpm"
oracle_java_rpm_url: "http://download.oracle.com/otn-pub/java/jdk/{{oracle_java_version}}u{{oracle_java_version_update}}-b{{oracle_java_version_build}}/{{oracle_java_version_uuid}}/{{oracle_java_rpm_filename}}"